import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Hero from "../sections/Hero";
import Nav from "../components/Nav";
import Second from "../sections/Second";
import Third from "../sections/Third";
import Fourth from "../sections/Fourth";
import Fifth from "../sections/Fifth";
import { useRouter } from "next/router";

// inspiration : https://www.behance.net/gallery/144881279/Aquarium-Seafood-restaurant-website?tracking_source=search_projects%7Crestaurant+website+design

const sectionStyles = `bg-slate-200 dark:bg-[#060c08] transition-all duration-300 relative`;

const page = (page: string) => (
  <span className="absolute bottom-5 left-2/4 -translate-x-2/4 font-nanum text-3xl text-[#060c08] dark:text-slate-200">
    {page}
  </span>
);

const Home: NextPage = () => {
  return (
    <div className="select-none w-screen max-w-[100%] h-screen overflow-y-hidden overflow-x-hidden scroll-smooth">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Nav />

      <section id="1" className={sectionStyles}>
        <Hero />
        {page("I")}
      </section>
      <section id="2" className={sectionStyles}>
        <Second />
        {page("II")}
      </section>
      <section id="3" className={sectionStyles}>
        <Third />
        {page("III")}
      </section>
      <section id="4" className={sectionStyles}>
        <Fourth />
        {page("IV")}
      </section>
      <section id="5" className={sectionStyles}>
        <Fifth />
        {page("V")}
      </section>
    </div>
  );
};

export default Home;
